### ISSUE TITLE
Use the correct registry setting to disable IPV6 

### ISSUE THREAD

**Issue by ricardogaspar2** [martezr/puppet-windows_disable_ipv6#3]
According to Microsoft (https://support.microsoft.com/en-us/help/929852/how-to-disable-ipv6-or-its-components-in-windows) the correct setting for disabling IPV6 is 0xff instead of 0xFFFFFFFF.

**Comment by martezr** [comment]
I'll make that change this week when I hopefully push an updated version of the module.

**Comment by ricardogaspar2** [comment]
Did you manage to update it?

**Comment by martezr** [comment]
Sorry about that, I was busy with a project last week and didn't have a chance to get to this.
